/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BigNumber from "bignumber.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";
export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}
export type Deposit = ContractEventLog<{
  dst: string;
  wad: string;
  0: string;
  1: string;
}>;
export type Withdrawal = ContractEventLog<{
  src: string;
  wad: string;
  0: string;
  1: string;
}>;
export interface IWETH extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IWETH;
  clone(): IWETH;
  methods: {
    withdraw(
      wad: number | string | BigNumber
    ): NonPayableTransactionObject<void>;

    deposit(): PayableTransactionObject<void>;
  };
  events: {
    Deposit(cb?: Callback<Deposit>): EventEmitter;
    Deposit(options?: EventOptions, cb?: Callback<Deposit>): EventEmitter;

    Withdrawal(cb?: Callback<Withdrawal>): EventEmitter;
    Withdrawal(options?: EventOptions, cb?: Callback<Withdrawal>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Deposit", cb: Callback<Deposit>): void;
  once(event: "Deposit", options: EventOptions, cb: Callback<Deposit>): void;

  once(event: "Withdrawal", cb: Callback<Withdrawal>): void;
  once(
    event: "Withdrawal",
    options: EventOptions,
    cb: Callback<Withdrawal>
  ): void;
}
