/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BigNumber from "bignumber.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";
export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface OpOracle extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): OpOracle;
  clone(): OpOracle;
  methods: {
    DECIMALS(): NonPayableTransactionObject<string>;

    baseFee(): NonPayableTransactionObject<string>;

    decimals(): NonPayableTransactionObject<string>;

    gasPrice(): NonPayableTransactionObject<string>;

    getL1Fee(_data: string | number[]): NonPayableTransactionObject<string>;

    getL1GasUsed(_data: string | number[]): NonPayableTransactionObject<string>;

    l1BaseFee(): NonPayableTransactionObject<string>;

    overhead(): NonPayableTransactionObject<string>;

    scalar(): NonPayableTransactionObject<string>;

    version(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
